### PR TITLE
print out the percentage variation for each pair

### PR DESCRIPTION
**Pull request by nmenescardi**
added a percentage variation to have a reference of the change for each pair

image

### CODE REVIEW

**Comment by triat** [comment]
Hello @nmenescardi,

This is an interesting feature you're proposing here. Unfortunately, I can see that the CI has failed on some part, can I ask you to fix them before we can merge this? 

From what I can see, you have a line too long (>100) and you do not have any mypy definition on your function. If you need help to fix them, let me know

**Comment by nmenescardi** [comment]
hi @triat , I fixed some linting issues but not sure about the last one: 
image

do you know how I can replicate same linting validation on a local environment?

**Comment by triat** [comment]
That's a good point, I haven't explained the rules.

You can basically run all the following commands:
```
mypy scripts
pylint scripts
flake8 scripts
black --check scripts
isort --check --diff scripts
```

All the requirements are in the `requirements-dev.txt`

I'm using `black` to formate the code, you can also use it by doing `black <file>`

**Comment by nmenescardi** [comment]
thanks for the steps. Seams to be fixed now

**Review by triat — APPROVED** [review]
Thank you for your participation and willing improve this script! 👍

**Pull request merged**
